# Generated by Django 5.1 on 2024-08-21 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accessories', 'Accessories'), ('clothing', 'Clothing'), ('arts', 'Arts'), ('handicrafts', 'Handicrafts'), ('all', 'All')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='product_images/front')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='product_images/back')),
                ('for_whom', models.CharField(choices=[('parents', 'Parents'), ('friends', 'Friends'), ('men', 'Men'), ('women', 'Women'), ('siblings', 'Siblings')], max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
