# Generated by Django 5.1 on 2024-09-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_whom',
        ),
    ]
