# Generated by Django 5.1 on 2024-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='id_proof_number',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='id_proof_image',
            field=models.ImageField( upload_to='id_proofs/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
