# Generated by Django 5.1 on 2024-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_sellerprofile_id_proof_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_proof_image',
            field=models.ImageField(default='id_proofs/cat.jpg', upload_to='id_proofs/'),
        ),
    ]
