# Generated by Django 5.1 on 2024-10-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_sellerprofile_id_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_proof_image',
            field=models.ImageField(blank=True, default='id_proofs/cat.jpg', null=True, upload_to='id_proofs/'),
        ),
    ]
